### ISSUE TITLE
The height of the UIToolkit dropdown cannot be limited

### ISSUE THREAD

**Issue by detzt** [detzt/BugReporting#4]

**Comment by detzt** [comment]
Bug report sent:

**What happened**
A UI Toolkit dropdown field that has many choices extends below the visible screen.
This is the first issue, as it should switch to scrolling before that and keep the list shorter by default.
But there are also situations when a developer wants to keep the list even shorter by choice.
However, setting the max-height property is not respected as it is overwritten by an internal script.
Styling only the child elements leaves the border.
Styling the parent element has no effect.
Modifications are severely limited in general as the choices list is drawn on a separate VisualElement outside of the hierarchy that gets generated during runtime.

**How can we reproduce it using the example you attached**

1. Run the SampleScene.
2. Try to select Entry 25.
3. Try to limit the height of the expanded dropdown by writing something in Stylesheet.uss.

**Comment by detzt** [comment]
Fixed in Unity 6000.0.0

Height is automatically limited to screen and further limiting also works by using:
```css
.unity-base-dropdown__container-outer {
  max-height: 25%;
}
```

**Comment by staythirsty90** [comment]
using Unity 6000.0.43f1. I am unable to limit the size of the Dropdown using USS:

`.unity-base-dropdown__container-outer {
  max-height: 25%;
}`

and the overflowing off the screen has not been fixed, if the game is in a Windowed state. I cannot believe how bad this UI system is

**Comment by detzt** [comment]
@staythirsty90 This is just a notebook kind of repo for me to keep track of the bug reports I've sent to Unity. If you want to get this fixed, please sent a bug report to Unity directly using their bug reporter tool.
